export const FETCH_SKILLS = "SKILLS/FETCH_SKILLS"
export const ADD_SKILL = "SKILLS/ADD_SKILL"
export const DELETE_SKILL = "SKILLS/DELETE_SKILL"
export const CHANGE_SKILL = "SKILLS/CHANGE_SKILL"

export const SHOW_LOADING = "APP/SHOW_LOADING"
export const HIDE_LOADING = "APP/HIDE_LOADING"