export const FETCH_SKILLS = "SKILLS/FETCH_SKILLS"
export const ADD_SKILL = "SKILLS/ADD_SKILL"
export const DELETE_SKILL = "SKILLS/DELETE_SKILL"
export const UPDATE_SKILL = "SKILLS/UPDATE_SKILL"
export const SHOW_UPDATE_SKILL_FORM = "SKILLS/SHOW_UPDATE_SKILL_FORM"
export const HIDE_UPDATE_SKILL_FORM = "SKILL/HIDE_UPDATE_SKILL_FORM"

export const SHOW_LOADING = "APP/SHOW_LOADING"
export const HIDE_LOADING = "APP/HIDE_LOADING"

export const FETCH_TASKS = "TASKS/FETCH_TASKS"
export const ADD_TASK = "TASKS/ADD_TASK"
export const DELETE_TASK = "TASKS/DELETE_TASK"
export const UPDATE_TASK = "TASKS/UPDATE_TASK"

export const FETCH_PROFILE = "PROFILE/FETCH_PROFILE"
export const UPDATE_PROFILE = "PROFILE/EDIT_PROFILE"

export const ADD_TASK_TO_UNCOMPLETED = "TODO/ADD_TASK_TO_UNCOMPLETED"
export const DELETE_TASK_FROM_UNCOMPLETED = "TODO/DELETE_TASK_FROM_UNCOMPLETED"
export const ADD_TASK_TO_COMPLETED = "TODO/ADD_TASK_TO_COMPLETED"
export const DELETE_TASK_FROM_COMPLETED = "TODO/DELETE_TASK_FROM_COMPLETED"
